Repository googleapis/java-billing, pull requests merged in 2020-09, with the labels that each got.

#174 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: cloudbilling, cla: yes, context: full

#176 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#188 chore: regenerate README
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#194 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#196 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: cloudbilling, automerge, cla: yes

#202 chore: regenerate templates
  .github/readme/synth.py
  .github/workflows/auto-release.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#204 build: rename samples lint workflow to checkstyle to disambiguate branch protection with unit lint
  .github/workflows/samples.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
