Repository googleapis/java-billing, pull requests merged in 2020-06, with the labels that each got.

#104 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#112 chore: regenerate with updated protoc
  README.md
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/AggregationInfo.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/BillingAccount.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/Category.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/CreateBillingAccountRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/GetBillingAccountRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/GetProjectBillingInfoRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListBillingAccountsRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListBillingAccountsResponse.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListProjectBillingInfoRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListProjectBillingInfoResponse.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListServicesRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListServicesResponse.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListSkusRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ListSkusResponse.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/PricingExpression.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/PricingInfo.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/ProjectBillingInfo.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/Service.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/Sku.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/UpdateBillingAccountRequest.java
  proto-google-cloud-billing-v1/src/main/java/com/google/cloud/billing/v1/UpdateProjectBillingInfoRequest.java
  synth.metadata
Labels: automerge, cla: yes, context: partial

#114 chore(java_templates): add default CODEOWNERS files for samples reviews
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#117 chore: turn on renovate-bot master issue for java repos
  renovate.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#119 build(java): skip lint on samples directory
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#124 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#128 ci: switch to secret manager for samples/integration tests
  .kokoro/build.sh
  .kokoro/nightly/integration.cfg
  .kokoro/nightly/samples.cfg
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/integration.cfg
  .kokoro/presubmit/samples.cfg
  .kokoro/trampoline.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#129 feat(deps): adopt flatten plugin and google-cloud-shared-dependencies
  .gitignore
  google-cloud-billing/pom.xml
  grpc-google-cloud-billing-v1/pom.xml
  pom.xml
  proto-google-cloud-billing-v1/pom.xml
Labels: cla: yes

#134 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none

#144 chore: regenerate README versions
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: none
