Repository googleapis/java-billing, pull requests merged in 2021-05, with the labels that each got.

#398 build(java): switch to release-please for release tagging
  .github/release-please.yml
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: none

#399 chore: add enumeration data type to .repo-metadata.json
  .repo-metadata.json
Labels: api: cloudbilling, automerge, cla: yes

#400 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#404 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbilling, automerge, cla: yes

#407 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbilling, automerge, cla: yes

#408 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#410 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbilling, automerge, cla: yes

#411 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#413 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#416 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: cloudbilling, automerge, cla: yes, context: full

#419 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: cloudbilling, automerge, cla: yes
